name: Gamejob to Notion (hourly)
on:
  schedule:
    - cron: "0 * * * *"   # 매 정시마다 (UTC 기준)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run crawler
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python gamejob_to_notion.py --list-url "https://www.gamejob.co.kr/Recruit/joblist?menucode=duty&duty=1" --pages 0 --delay 1.5
